shell.run("rm", "*.lua")
shell.run("rm", "utils controllers tasks")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/controllTurtles.lua")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/startup.lua")
shell.run("mkdir", "utils controllers tasks")
shell.run("cd", "utils")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/utils/block.lua")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/utils/gps.lua")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/utils/mining.lua")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/utils/quarry.lua")
shell.run("cd", "..")
shell.run("cd", "controllers")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/controllers/receive.lua")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/controllers/send.lua")
shell.run("cd", "..")
shell.run("cd", "tasks")
shell.run("wget","https://raw.githubusercontent.com/stealthHat/turtle-scripts/new-structure/tasks/manager.lua")
shell.run("cd", "..")
shell.run("clear")

os.loadAPI('/utils/gps')

calibrate()
