local blocks = {}

blocks.useless_blocks = "quark:limestone "
  .. "quark:root_item "
  .. "quark:smooth_basalt "
  .. "cavesandcliffs:tuff "
  .. "cavesandcliffs:raw_copper "
  .. "byg:scoria_cobblestone "
  .. "byg:soapstone "
  .. "byg:rocky_stone "
  .. "create:limestone "
  .. "create:ochrum "
  .. "create:scoria "
  .. "create:scorchia "
  .. "create:crimsite "
  .. "create:veridium "
  .. "create:asurine "
  .. "create:weathered_limestone_cobblestone "
  .. "minecraft:calcite "
  .. "minecraft:soul_sand "
  .. "minecraft:soul_soil "
  .. "minecraft:soorchia "
  .. "minecraft:magma_block  "
  .. "minecraft:andesite "
  .. "minecraft:netherrack "
  .. "minecraft:nether_bricks "
  .. "minecraft:blackstone "
  .. "minecraft:basalt"
  .. "minecraft:pointed_dripstone "
  .. "minecraft:dripstone_block "
  .. "minecraft:cobblestone "
  .. "minecraft:dirt "
  .. "minecraft:tuff "
  .. "minecraft:gravel "
  .. "minecraft:clay_ball"
  .. "minecraft:smooth_basalt "
  .. "minecraft:cobbled_deepslate "
--  .. "minecraft:lapis_lazuli "
--  .. "minecraft:sand "
--  .. "minecraft:redstone "
--  .. "minecraft:flint "
--  .. "minecraft:granite "
--  .. "minecraft:diorite "
--  .. "minecraft:raw_copper "
--  .. "quark:cobbled_deepslate "
--  .. "cavesandcliffs:cobbled_deepslate  "
--  .. "consistency_plus:cobbled_andesite "
--  .. "consistency_plus:cobbled_tuff "
--  .. "consistency_plus:cobbled_granite "
--  .. "consistency_plus:cobbled_dripstone "
--  .. "consistency_plus:cobbled_diorite "
--  .. "consistency_plus:cobbled_calcite "
--  .. "consistency_plus:cobbled_sandstone "

blocks.fuel_blocks = "minecraft:charcoal minecraft:coal thermal:coal_coke projecte:aeternalis_fuel_block"

return blocks
