local blocks = {}

blocks.useless_blocks = "quark:limestone "
  .. "create:limestone "
  .. "create:ochrum "
  .. "create:scoria "
  .. "create:scorchia "
  .. "create:crimsite "
  .. "create:veridium "
  .. "create:asurine "
  .. "consistency_plus:cobbled_andesite "
  .. "consistency_plus:cobbled_tuff "
  .. "consistency_plus:cobbled_granite "
  .. "consistency_plus:cobbled_dripstone "
  .. "consistency_plus:cobbled_diorite "
  .. "consistency_plus:cobbled_calcite "
  .. "consistency_plus:cobbled_sandstone "
  .. "minecraft:calcite "
  .. "minecraft:soul_sand "
  .. "minecraft:soul_soil "
  .. "minecraft:soorchia "
  .. "minecraft:magma_block  "
  .. "minecraft:raw_copper "
  .. "minecraft:smooth_basalt "
  .. "minecraft:flint "
  .. "minecraft:cobbled_deepslate "
  .. "minecraft:netherrack "
  .. "minecraft:nether_bricks "
  .. "minecraft:blackstone "
  .. "minecraft:basalt"
  .. "minecraft:pointed_dripstone "
  .. "minecraft:dripstone_block "
  .. "minecraft:diorite "
  .. "minecraft:andesite "
  .. "minecraft:cobblestone "
  .. "minecraft:dirt "
  .. "minecraft:tuff "
  .. "minecraft:gravel "
  --    "minecraft:sand " ..
  --    "minecraft:redstone " ..
  --    "minecraft:lapis_lazuli " ..
  .. "minecraft:granite "
  .. "minecraft:clay_ball"

blocks.fuel_blocks = "minecraft:charcoal minecraft:coal projecte:aeternalis_fuel_block"

return blocks
